server:
  port: 8866
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sdu?serverTimezone=Asia/Shanghai
    username: root
    password: Jc20031230
#    username: sdu
#    password: 111111

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations: classpath:mapper/*.xml

weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wx98d66167a6aa99d4
  secret: 9b2aa466ec003aba687ccf34d0ae6a55
#
#userImagesFilePath: C:\Users\Jc\Desktop\sdu\img\
#coverImagesFilePath: C:\Users\Jc\Desktop\sdu\img\

userImagesFilePath: user/
coverImagesFilePath: cover/